repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
    -   id: setup-cfg-fmt
        args: [--include-version-classifiers]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
      - id: black
        language_version: python3
