-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.15.0
    hooks:
    -   id: setup-cfg-fmt
- repo: https://github.com/psf/black
  rev: 19.10b0 # Replace by any tag/version: https://github.com/psf/black/tags
  hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+