name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.5", "3.6", "3.7", "3.8"]
        os: [ubuntu-latest, windows-latest]
        include:
          - python: "3.5"
            tox_env: "py35"
          - python: "3.6"
            tox_env: "py36"
          - python: "3.7"
            tox_env: "py37"
          - python: "3.8"
            tox_env: "py38"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip setuptools
        pip install tox
    - name: Test
      run: |
        tox -e ${{ matrix.tox_env }}
  
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0